# Create by
# [Chayaphon Bunyakan (Neer) 62070503412]
# From team Valid

ifeq ($(OSTYPE),WINDOWS)
	EXECEXT =.exe
	COMP	=__MINGCC__
	PLATFORM	=mingw
else
	EXECEXT =
	COMP	=__GCC__
	PLATFORM	=linux
endif

EXECUTABLES= main$(EXECEXT)

all : $(EXECUTABLES)

linkedListQueue.o :	linkedListQueue.c abstractQueue.h
	gcc -c linkedListQueue.c

minPriorityQueue.o :	minPriorityQueue.c minPriorityQueue.h
	gcc -c minPriorityQueue.c

flightNetwork.o :	flightNetwork.c abstractNetwork.h abstractQueue.h flightFinder.h
	gcc -c flightNetwork.c

flightFinder.o :	flightFinder.c abstractNetwork.h flightNetwork.h
	gcc -c flightFinder.c

main.o :	main.c abstractNetwork.h networkBuilder.h
	gcc -c main.c

networkBuilder.o :	networkBuilder.c abstractNetwork.h networkBuilder.h
	gcc -c networkBuilder.c


main$(EXECEXT) : main.o flightNetwork.o linkedListQueue.o networkBuilder.o minPriorityQueue.o flightFinder.o
	gcc -o main$(EXECEXT) main.o flightNetwork.o \
              linkedListQueue.o networkBuilder.o minPriorityQueue.o flightFinder.o


clean : 
	-rm *.o
	-rm $(EXECUTABLES) 
